### PR TITLE
Fix compilation on Ubuntu 18.04.

### LINKED ISSUE #1: Fails to compile on ubuntu 18.04
rd is not building on my system (Ubuntu 18.04). Steps to reproduce:

```
git clone git@github.com:sidkshatriya/rd.git
cd rd/
cargo build
```

Truncated error:
```
error[E0412]: cannot find type `itimerspec` in module `kernel`                                                                                                                                                                         [68/712]
    --> src/kernel_abi.rs:709:33
     |
709  |         assert_eq_size!(kernel::itimerspec, itimerspec);
     |                                 ^^^^^^^^^^
     |
    ::: /home/josh/Projects/rd/target/debug/build/rd-593c103ccfe8f56f/out/kernel_bindings_generated.rs:6389:1
     |
6389 | pub struct timespec {
     | ------------------- similarly named struct `timespec` defined here
     |
help: a struct with a similar name exists
     |
709  |         assert_eq_size!(kernel::timespec, itimerspec);
     |                                 ^^^^^^^^
help: consider importing one of these items
     |
539  |         use crate::session::task::task_inner::x86::itimerspec;
     |
539  |         use crate::util::native_arch::itimerspec;
     |
539  |         use libc::itimerspec;
     |

error[E0412]: cannot find type `itimerspec` in module `kernel`
    --> src/kernel_abi.rs:710:34
     |
710  |         assert_eq_align!(kernel::itimerspec, itimerspec);
     |                                  ^^^^^^^^^^
     |
    ::: /home/josh/Projects/rd/target/debug/build/rd-593c103ccfe8f56f/out/kernel_bindings_generated.rs:6389:1
     |
6389 | pub struct timespec {
     | ------------------- similarly named struct `timespec` defined here
     |
help: a struct with a similar name exists
     |
710  |         assert_eq_align!(kernel::timespec, itimerspec);
     |                                  ^^^^^^^^
help: consider importing one of these items
     |
539  |         use crate::session::task::task_inner::x86::itimerspec;
     |
539  |         use crate::util::native_arch::itimerspec;
     |
539  |         use libc::itimerspec;
     |

error[E0412]: cannot find type `statx_timestamp` in module `kernel`
   --> src/kernel_abi.rs:780:33
    |
780 |         assert_eq_size!(kernel::statx_timestamp, statx_timestamp);
    |                                 ^^^^^^^^^^^^^^^ not found in `kernel`
    |
help: consider importing one of these items
    |
539 |         use crate::session::task::task_inner::x86::statx_timestamp;
    |
539 |         use crate::util::native_arch::statx_timestamp;
    |
539 |         use libc::statx_timestamp;
    |

error[E0412]: cannot find type `statx_timestamp` in module `kernel`
   --> src/kernel_abi.rs:781:34
...
```

rust version: 
```
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.48.0-nightly (bbc677480 2020-09-18)
```

### PR DESCRIPTION
**Pull request by khuey**
Fixes #1.

### CODE REVIEW

**Comment by sidkshatriya** [comment]
Thanks @khuey !
